title: Short URL
description: Encurtador de URL
url: https://h4y.uk
baseurl: "/"
link_default: https://t.me/gore24hrs
url_adsense: https://bitcurioso.com

campaign_status: false
campaign_message: 'Olá visitante, no momento estamos efetuando uma manutenção em nosso site. Por favor, tente mais tarde.'

permalink: pretty

highlighter: rouge
markdown: kramdown
kramdown:
  html_to_native: true
  auto_ids: false

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
