site: Daily Dose Of Gore
url: https://h4y.uk
title: Daily Dose Of Gore
description: Daily Dose Of Gore
tagline: Daily Dose Of Gore...
lang: pt_BR
author: groupunknown
google_analytics: UA-120280297-1
google_analytics_status: false

webmaster_verifications:
  #google: BHhjherZoAFIqjGDO05JmCzgLmKjOIr-pD8N7TYvkg8
  #bing: 
  #alexa: 
  #yandex: 
  #baidu: 

baseurl: ""
permalink: pretty
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
paginate: 10
paginate_path: /page/:num/
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
paginate: 20
paginate_path: /page/:num/
