site: Agregador™
url: https://agregador.github.io
title: Short URL
description: Encurtador de URL
tagline: Encurtador de URL
lang: pt_BR
link_default: https://t.me/gore24hrs

permalink: pretty
baseurl: ""

highlighter: rouge
markdown: kramdown
kramdown:
  html_to_native: true
  auto_ids: false

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults: